name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest 

        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Check out code
              uses: actions/checkout@v4
            
            - name: Set up go
              uses: actions/setup-go@v5
              with:
                go-version: "1.23.0"
            
            - name: Install Goose
              run: go install github.com/pressly/goose/v3/cmd/goose@latest
            
            - name: Build application
              run:  ./scripts/buildprod.sh

            - name: Run Migrations
              run: ./scripts/migrateup.sh
            
            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
        
            - name: Upload build to gcloud
              run:  gcloud builds submit --tag australia-southeast1-docker.pkg.dev/notely-449916/notely-ar-repo/danilovict2/notely:latest .
           
            - name: Deploy to Cloud Run
              run:  gcloud run deploy notely --image australia-southeast1-docker.pkg.dev/notely-449916/notely-ar-repo/danilovict2/notely:latest --region us-central1 --allow-unauthenticated --project notely-449916 --max-instances=4
